#!/bin/bash

i3status | while :
do
	 read line
	 
	 latest_char=${line: -1}
	 if [ $latest_char == "}" ]
	 then
		echo "$line" || exit 1
	 elif [ $latest_char == "]" ]
	 then
		lang=$(eval "~/Programs/xkblayout-state/xkblayout-state print \"%s\"")
		echo "${line::-1},{\"name\":\"lang\",\"full_text\":\"lang $lang \"}]" || exit 1
	 else
		echo "$line" || exit 1
	 fi		
done

